# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: first-init
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: create-db
    init: RUN mysql -e "CREATE DATABASE userauth;"


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
